server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "1ca67cbccbbcba715a9dd252fc221741ef808143ba94d7b01d717b0389bd4ea4f680250033cfd457d1d0a1c9a79046bde8771a1d24345a3b63695787b466be2d"
  application:
    name: "crediya-solicitud-prestamo"
  devtools:
    add-properties: false
  r2dbc:
    host: db_solicitudes
    port: 5432
    database: "crediya-solicitud-prestamo"
    schema: "public"
    username: "postgres"
    password: "postgres"
  sql:
    init:
      mode: "always"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
logging:
  level:
    root: "INFO"
    co.com.pragma: "TRACE"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:9001"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
