server:
  port: 8080
spring:
  application:
    name: "crediya-solicitud-prestamo"
  devtools:
    add-properties: false
  r2dbc:
    host: localhost
    port: 5432
    database: crediya-solicitud-prestamo
    schema: public
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
